table Kostenstellen
	lineageTag: cd35dd34-efb6-4ffb-a1b2-9cb3c6b16f85

	column Kostenstellen
		dataType: int64
		formatString: 0
		lineageTag: 4e6ae6ac-a8f1-430b-b095-390d9730d4d8
		summarizeBy: none
		sourceColumn: Kostenstellen

		annotation SummarizationSetBy = Automatic

	column Kostenstellen-und-Name
		dataType: string
		lineageTag: dd479f5a-fa42-4502-9f0b-a16932037142
		summarizeBy: none
		sourceColumn: Kostenstellen-und-Name

		annotation SummarizationSetBy = Automatic

	column Kostenstellen-Ebene1
		dataType: string
		lineageTag: d87ce126-df05-4a7a-93a2-8bfea484fa5d
		summarizeBy: none
		sourceColumn: Kostenstellen-Ebene1

		annotation SummarizationSetBy = Automatic

	column Kostenstellen-Ebene2
		dataType: string
		lineageTag: 7084a8f9-17c2-40eb-b86d-2ec652bc591d
		summarizeBy: none
		sourceColumn: Kostenstellen-Ebene2

		annotation SummarizationSetBy = Automatic

	partition Kostenstellen = m
		mode: import
		source =
				let
				    Quelle = Sql.Databases("6aiowjgnb6lu5iguqrukqsu6sa-6mi7yii457fuxbvj2h6z5byt5u.datawarehouse.fabric.microsoft.com"),
				    LH_Hoteldaten = Quelle{[Name="LH_Hoteldaten"]}[Data],
				    dbo_Kostenstellen = LH_Hoteldaten{[Schema="dbo",Item="Kostenstellen"]}[Data],
				    #"Gefilterte Zeilen" = Table.SelectRows(dbo_Kostenstellen, each [Kostenstellen] <> null and [Kostenstellen] <> ""),
				    #"Entfernte Duplikate" = Table.Distinct(#"Gefilterte Zeilen", {"Kostenstellen"})
				in
				    #"Entfernte Duplikate"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

