table 'Data Date'
	lineageTag: 532c89d6-8cef-4175-a91a-a6700319fb03

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c1934a1d-bb67-4495-acee-48e80f81ba0e
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: b0acc659-59b8-46d4-b96d-9c6794fb1e55
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 97c558b5-9714-4b4f-aca5-2566805b4650
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter'
		dataType: string
		lineageTag: a7709aff-acec-4a97-afa2-7527362d44cb
		summarizeBy: none
		sourceColumn: Year Quarter

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter Number'
		dataType: int64
		formatString: 0
		lineageTag: fcd9d365-4bd5-4df4-bc06-755f342a00a7
		summarizeBy: none
		sourceColumn: Year Quarter Number

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 8a193a76-b61b-4939-a5f0-673187e52043
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: string
		lineageTag: eaefa085-9ffb-4deb-b02a-bd077b9dad83
		summarizeBy: none
		sourceColumn: Year Month
		sortByColumn: 'Month Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Year Month Short'
		dataType: string
		lineageTag: 4a99cc2d-8d33-4302-a042-a23a8d992c3b
		summarizeBy: none
		sourceColumn: Year Month Short
		sortByColumn: 'Year Month Number'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Year Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 095359fd-ad80-4676-af06-048e91851768
		summarizeBy: none
		sourceColumn: Year Month Number

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 7e2cb38c-d3ce-4b55-ab43-c64dbbcf3eb3
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month Short'
		dataType: string
		lineageTag: 9f2655cf-33ab-41f0-b679-b96f2f5bbce9
		summarizeBy: none
		sourceColumn: Month Short

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 275dc793-1386-4000-b9eb-b76283c654a5
		summarizeBy: none
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: string
		lineageTag: d4c83d9d-7d7a-4056-8566-b14334cae29d
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Short'
		dataType: string
		lineageTag: 82a70618-efba-44e2-bfe7-a713bbea4d8a
		summarizeBy: none
		sourceColumn: Day of Week Short

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Number'
		dataType: int64
		formatString: 0
		lineageTag: dab1536c-3474-45e4-9764-f7a655c660e7
		summarizeBy: none
		sourceColumn: Day of Week Number

		annotation SummarizationSetBy = Automatic

	column 'Working Day'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8957c354-1655-4e94-ba20-22409062f086
		summarizeBy: none
		sourceColumn: Working Day

		annotation SummarizationSetBy = Automatic

	column 'Working Day Number'
		dataType: int64
		formatString: 0
		lineageTag: 76557262-f948-4b1b-992e-24278aa92dde
		summarizeBy: none
		sourceColumn: Working Day Number

		annotation SummarizationSetBy = Automatic

	partition 'Data Date-69d102da-8d4f-4cca-83e9-c06c34d5de6c' = m
		mode: import
		source =
				let
				    Quelle = Sql.Database("akdbserver.database.windows.net", "Contoso10K"),
				    Data_Date = Quelle{[Schema="Data",Item="Date"]}[Data],
				    #"Entfernte Spalten" = Table.RemoveColumns(Data_Date,{"Data.Orders"})
				in
				    #"Entfernte Spalten"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

