table 'Data Product'
	lineageTag: 63560950-0475-48e0-bd93-4c8d3d18e04a

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 1e557625-7e33-4390-bb98-ff6638c8d048
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column 'Product Code'
		dataType: string
		lineageTag: f074fe6f-6f2f-4172-9dd2-6330d3aad831
		summarizeBy: none
		sourceColumn: Product Code

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 13d7f981-506a-483e-8019-6f861a3c4d54
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Manufacturer
		dataType: string
		lineageTag: 3ffc176a-00d4-442d-a489-899200e013e5
		summarizeBy: none
		sourceColumn: Manufacturer

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 4d886ff9-9a28-4852-9cf5-c17eb894a934
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 5b499ba9-8259-4e64-b4f0-766d37a34dfe
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column 'Weight Unit Measure'
		dataType: string
		lineageTag: caa927e8-9ecf-41c2-b31b-92e083da872a
		summarizeBy: none
		sourceColumn: Weight Unit Measure

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: double
		lineageTag: 0ee12b03-d8f0-4820-86f8-e6a23a29c6dd
		summarizeBy: none
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Cost'
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 54e97b68-b64e-4361-b42b-a24ac164bd07
		summarizeBy: none
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"de-DE"}

	column 'Unit Price'
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 205c22a1-4602-4d94-b9ea-28f12dbbd34c
		summarizeBy: none
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"de-DE"}

	column 'Subcategory Code'
		dataType: string
		lineageTag: ddc7b970-7d6c-4ef3-a9eb-57d900b279b2
		summarizeBy: none
		sourceColumn: Subcategory Code

		annotation SummarizationSetBy = Automatic

	column Subcategory
		dataType: string
		lineageTag: eb6beea5-5017-4d0a-ac71-3a3333b0ad02
		summarizeBy: none
		sourceColumn: Subcategory

		annotation SummarizationSetBy = Automatic

	column 'Category Code'
		dataType: string
		lineageTag: fdc66545-358b-4192-9d0c-25628deda39d
		summarizeBy: none
		sourceColumn: Category Code

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 6f31524f-783e-448c-8229-524c6dcdd4c3
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition 'Data Product-09d301ec-255d-4202-917c-9c37b9c12e49' = m
		mode: import
		source =
				let
				    Quelle = Sql.Database("akdbserver.database.windows.net", "Contoso10K"),
				    Data_Product = Quelle{[Schema="Data",Item="Product"]}[Data],
				    #"Entfernte Spalten" = Table.RemoveColumns(Data_Product,{"Data.OrderRows"})
				in
				    #"Entfernte Spalten"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

